version: "2.0"

services:
  scrapper:
    build: ./scrapper
    volumes:
      - ./scrapper:/scrapper
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    build: ./mysql
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tts
  phpmyadmin:
    build: ./phpmyadmin
    ports:
      - 4000:80
    links:
      - mysql:db